services:
  app:
    container_name: app
    build:
      context: .
      target: development
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start:dev
